# Site settings
title: Dan Visintainer
email: dan@danvisintainer.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.danvisintainer.com" # the base hostname & protocol for your site
twitter_username: dviz
github_username:  danvisintainer
paginate: 8
excerpt_separator: "<!-- more -->"

# Build settings
markdown: kramdown

gems:
- jekyll-paginate
- fastimage
- nokogiri
